
import React from "react";
import axios from "axios";
import Head from 'next/head';
import { useRouter } from 'next/router';
// import { makeStyles } from '@material-ui/core/styles';
import { Card, CardContent, Typography, Button } from '@material-ui/core';
import styles from '../../../styles/news.module.scss';
import { Header } from '../../../containers/Header/Header';
import { Footer } from '../../../containers/Footer/Footer';
import { Main } from '../../../containers/Main/Main';
import getPosts from '../../../services/posts.service';
import { getStaticPaths } from '../../../translations/utils';


// const useStyles = makeStyles({
//   root: {
//     minWidth: 275,
//   },
//   bullet: {
//     display: 'inline-block',
//     margin: '0 2px',
//     transform: 'scale(0.8)',
//   },
//   title: {
//     fontSize: 14,
//   },
//   pos: {
//     marginBottom: 12,
//   },
// });
function News({ containerRef, posts, title, categorie, info, ...props}) {
  const { asPath } = useRouter();
  // const classes = useStyles();
  return (
    <div className={styles.container} data-scroll-container ref={containerRef} id='app'>
      <Head>
        <title>{info.title.rendered}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main className={styles['news-wrapper']} {...props}>
        <h1>{info.title.rendered}</h1>
        {posts.map(el => (
          <Card className={styles['news-card']} variant="outlined" key={el.id}>
            <CardContent>
              <Typography color="textSecondary" gutterBottom>
                {el.title.rendered}
              </Typography>
              <Button href={`${asPath}${el.id}`}>Перейти</Button>
            </CardContent>
          </Card>
        ))}
      </Main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await getPosts().request;
  const posts = await res.data.filter(post => post.categories.includes(getPosts().categories.news));
  const pageInfo = await axios.get('https://stanford.kiev.ua/wp-json/wp/v2/pages/?slug=news');
  const info = await pageInfo.data[0];
  // const array = Object.keys(posts.routes);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
      categorie: 'news',
      info
    },
  }
}

export { getStaticPaths };

export default News;
