import 'normalize.css';
import '../styles/globals.css';
import React, { useEffect } from "react";
import Head from "next/dist/next-server/lib/head";
import gsap from 'gsap';
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ThemeProvider } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
// import { LocomotiveScrollProvider } from 'react-locomotive-scroll'
import theme from '../theme';
import 'locomotive-scroll/dist/locomotive-scroll.css';


function MyApp({ Component, pageProps }) {
  useEffect(() => {
    let scroll = null;
    import('locomotive-scroll').then((locomotiveModule) => {

      // eslint-disable-next-line new-cap
      scroll = new locomotiveModule.default({
        el: document.querySelector("[data-scroll-container]"),
        smooth: true,
        resetNativeScroll: true
      });
      React.createContext(scroll);
      setTimeout(() => {
        scroll.init();
      }, 100);
    });
    
    return () => {
      scroll.destroy();
      document.querySelector('.c-scrollbar').remove()
    }
  });

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      {/* <LocoContext.Provider value={ctx}> */}
        <Component gsap={gsap} ScrollTrigger={ScrollTrigger} {...pageProps}/>
      {/* </LocoContext.Provider> */}
    </ThemeProvider>
)
}

export default MyApp;
