import Head from 'next/head';
import { useState } from 'react';
import { SwipeableDrawer, Button } from '@material-ui/core';
// eslint-disable-next-line import/no-unresolved
import styles from '../styles/about.module.scss';
import { Header } from '../containers/Header/Header';
import { Footer } from '../containers/Footer/Footer';

export default function About() {
  const [state, setState] = useState({
    top: false,
    left: false,
    bottom: false,
    right: false,
  });
  const toggleDrawer = (anchor, open) => (event) => {
    if (event.type === 'keydown' && (event.key === 'Tab' || event.key === 'Shift')) {
      return;
    }

    setState({ ...state, [anchor]: open });
  };
  return (
    <div className={styles.container} id='app'>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
       <Button onClick={toggleDrawer('right', true)}>About US</Button>
        <SwipeableDrawer onClose={toggleDrawer('right', false)} anchor="right" open={state.right}>
          <ul>
            <li>Про Lorem нас1</li>
            <li>Про Lorem нас2</li>
            <li>Про Lorem нас3</li>
            <li>Про Lorem нас4</li>
            <li>Про Lorem нас5</li>
            <li>Про Lorem нас6</li>
            <li>Про Lorem нас7</li>
            <li>Про Lorem нас8</li>
            <li>Про Lorem нас9</li>
            <li>Про Lorem нас10</li>
          </ul>
        </SwipeableDrawer>
      </main>
      <Footer />
    </div>
  );
}
