import React from "react";
import Head from 'next/head';
import styles from '../styles/Contacts.module.scss';
import { Header } from '../containers/Header/Header';
import { Footer } from '../containers/Footer/Footer';
import { getGallery } from '../services/gallery.service';


function Gallery({ containerRef, posts }) {
  return (
    <div className={styles.container} data-scroll-container ref={containerRef} id='app'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main data-scroll-section>
        <h1>Contact Template</h1>
        {posts.map((post, index) => (
            <img alt="some" key={index} src={post.img.url}/>
        ))}
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
    // Call an external API endpoint to get posts.
    // You can use any data fetching library
    const res = await getGallery();
    const posts = await res.data;
    // const array = Object.keys(posts.routes);
    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
      props: {
        posts: posts.acf.block_2.gallery,
      },
    }
}
export default Gallery
