import React, {useContext, useRef} from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
import 'locomotive-scroll/dist/locomotive-scroll.css';
import FormControl from '@material-ui/core/FormControl';
import InputLabel from '@material-ui/core/InputLabel';
import NativeSelect from '@material-ui/core/NativeSelect';
import {useUpdateEffect} from "react-use";
import styles from '../styles/Home.module.scss';
import { ReactComponent as IntroIcon } from '../../public/smarto.svg';
import { Button } from '../components/UI/Button';
import { Header } from '../components/UI/Header/Header';
import { Footer } from '../components/UI/Footer/Footer';
// eslint-disable-next-line import/named
import {SmoothScrollContext} from '../contexts/SmoothScroll.context';

export default function Home() {
  const { scroll } = useContext(SmoothScrollContext);
  const scrollRef = useRef(null);
  const [selectId, setSelectId] = React.useState(1);
  
  useUpdateEffect(() => {
    scroll.update();
  });

  const handleChange = (event) => {
    setSelectId(+event.target.value);
  };
  
  function TabPanel(props) {
    const { children, value, index, ...other } = props;
    return (
      <div
        role="tabpanel"
        hidden={value !== index}
        id={`simple-tabpanel-${index}`}
        aria-labelledby={`simple-tab-${index}`}
        {...other}
      >
        {value === index && (
            children
        )}
      </div>
    );
  }

  TabPanel.propTypes = {
    children: PropTypes.node,
    index: PropTypes.any.isRequired,
    value: PropTypes.any.isRequired,
  };

  return (
    <div data-scroll-container className={styles.container} ref={scrollRef} id='app'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section data-scroll-section className={styles.main} >
          <IntroIcon width={400} height={200} />
          <h1 data-scroll className={styles.title}>Starting template</h1>
          <a href="#second-part">
            Go to second part
          </a>
          <Button data-scroll>Click me</Button>
          <FormControl>
            <InputLabel>LIVE камери</InputLabel>
            <NativeSelect
              value={selectId}
              onChange={handleChange}
              name="camers"
              >
              <optgroup label="outside">
                <option value={1}>camera 1</option>
              </optgroup>
              <optgroup label="inside">
                <option value={2}>camera 2.1</option>
                <option value={3}>camera 2.2</option>
              </optgroup>
            </NativeSelect>
          </FormControl>

          <TabPanel value={selectId} index={1} >
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Soluta nostrum vitae eaque dolores nam enim
            vel! Incidunt ea et veritatis eveniet maiores laborum reprehenderit fugiat voluptatum omnis quo.
            Repudiandae quod consectetur dolor quae autem cupiditate sint molestias eius totam! Optio eum
            maiores similique accusantium quisquam nemo veritatis dolor.
            Vitae fugit, maiores perferendis velit
            officiis consequatur dolores eaque illo, ad sit molestias suscipit,
            id exercitationem non aut dolore
            numquam! Dignissimos iste incidunt, rem sed explicabo quae natus error dicta quas architecto
            cupiditate aperiam reiciendis minima aliquid perspiciatis dolor laborum inventore tempora
            voluptatibus distinctio! Reprehenderit vel quia at quam voluptates? Error, iure corporis soluta
            porro illo fuga, perspiciatis quia assumenda nisi unde optio
            praesentium incidunt fugiat saepe. Sint
            iusto aliquam numquam in nam quasi omnis deleniti, ipsa officiis maiores quidem magni odio
            dignissimos earum perferendis modi quis adipisci autem deserunt error. Temporibus, aliquam minus
            natus voluptates labore quo at velit recusandae veritatis a.
            Hic laboriosam quis libero modi totam!
            Beatae, delectus vel ducimus quos, nesciunt facilis magni facere suscipit eius esse quibusdam
            inventore sit aperiam temporibus explicabo totam a ratione, enim ut neque rerum distinctio! Non
            distinctio voluptatibus sapiente, enim ullam est quo,
            magnam iure doloremque, sit consequatur vitae.
            Illo, odio distinctio.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore maxime
            odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          </TabPanel>
          <TabPanel value={selectId} index={2} >
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores autem
            commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore maxime odit,
            porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          </TabPanel>
          <TabPanel value={selectId} index={3} >
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores autem
            commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore maxime odit,
            porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores autem
            commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore maxime odit,
            porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores autem
            commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore maxime odit,
            porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          <p data-scroll>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam amet asperiores
            autem commodi consequuntur cum debitis doloremque dolores dolorum, ea inventore
            maxime odit, porro quam sed sint, ullam. Harum, soluta.
          </p>
          </TabPanel>
      </section>
      <Footer />
    </div>
  );
}
