
import React from "react";
import Head from 'next/head';
import { makeStyles } from '@material-ui/core/styles';
import { Card, CardContent, Typography, Button } from '@material-ui/core';
import styles from '../styles/news.module.scss';
import { Header } from '../containers/Header/Header';
import { Footer } from '../containers/Footer/Footer';

import getPosts from '../services/posts.service';

const useStyles = makeStyles({
  root: {
    minWidth: 275,
  },
  bullet: {
    display: 'inline-block',
    margin: '0 2px',
    transform: 'scale(0.8)',
  },
  title: {
    fontSize: 14,
  },
  pos: {
    marginBottom: 12,
  },
});
function News({ containerRef, posts, title, categorie }) {
  const classes = useStyles();
  return (
    <div className={styles.container} data-scroll-container ref={containerRef} id='app'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {posts.map(el => (
          <Card variant="outlined">
            <CardContent>
              <Typography className={classes.title} color="textSecondary" gutterBottom>
                {el.title.rendered}
              </Typography>
              <Button href={`${categorie}/${el.id}`}>Перейти</Button>
            </CardContent>
          </Card>
        ))}
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await getPosts().request;
  const posts = await res.data.filter(post => post.categories.includes(getPosts().categories.news));
  // const array = Object.keys(posts.routes);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
      categorie: 'news'
    },
  }
}

export default News;
