name: Deploy
on: 
  push:
    branches: [ langs ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: 185.65.244.35
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: cd newBuildReact && kill `cat ../proccess.txt` || git pull origin langs && npm run build && nohup node index.js & echo $! > ../proccess.txt