name: Deploy
on: 
  push:
    branches: [ langs ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: 185.65.244.35
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: cd newBuildReact && git pull origin langs && kill -9 `cat proccess.txt` && npm run build && cd ../ &&  nohup node /root/newBuildReact/node_modules/.bin/next start & echo $! > proccess.txt